version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:10
        environment:
          AWS_REGION: us-east-1
          NODE_ENV: production
    steps:
      - checkout
      - run: yarn
      - run: yarn xo
      - run: yarn prettier -l
